/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fhttzmshnhjigmsegkuq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodHR6bXNobmhqaWdtc2Vna3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNTA4NjcsImV4cCI6MjA3NDgyNjg2N30.D-wGQ8ddf5g3Ac-h_PcZKGhI8zFZ3ZAUIFyH_HLRs0U"